---

users_users:
  - user: CI
    name: "Ansible server"
    key: 
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGt0hAaUuZC9L7M00SjOO1+een110HKAtiJIUN5O8FzD ansible
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMwen6lHvz1QFveQB0y9vvvNArZUAQ8GrqARF8rpKCIC mitch@Office
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOLkxOgw2GXIm1ot/18IStuYku64pjYd6ARYbkXcm2Z9 mitch@laptop

  - user: mitch
    name: "Mitch"
    key: 
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMwen6lHvz1QFveQB0y9vvvNArZUAQ8GrqARF8rpKCIC mitch@Office
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOLkxOgw2GXIm1ot/18IStuYku64pjYd6ARYbkXcm2Z9 mitch@laptop

# users_admin_users: []
users_admin_users:
  - CI
  - mitch

# users_admin_groups: []
users_admin_groups:
  - sudo
  - admin
  - sshusers

# App users no sudo permission
# users_app_users:
#   - bob
# users_app_users: []

# users_app_groups:
#   - sshusers
# users_app_groups: []