---

- name: Ensure docker-compose is install
  ansible.builtin.package:
    name: docker-compose
    state: present

- name: Ensure docker is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Set up app directory
  ansible.builtin.file:
    path: /home/{{ users_app_users }}/{{ app_name }}
    state: directory
    mode: "0755"
    owner: "{{ users_app_users }}"
    group: "{{ users_app_users }}"
