---

# Users ssh keys
users_users:
  - user: CI
    name: "Ansible server"
    key: 
      - "{{ vault_ansible_ssh_key }}"

  - user: mitch
    name: "Mitch"
    key: 
      - "{{ vault_office_ssh_key }}"
      - "{{ vault_laptop_ssh_key }}"

# Admin users
users_admin_users:
  - CI
  - mitch

# Admin groups
users_admin_groups:
  - sudo
  - admin
  - sshusers

# App users
users_app_users: []

# App groups
users_app_groups: []

# Name of app
app_name: []