---

- name: Install base packages
  become: true
  ansible.builtin.apt:
    name:
      - qemu-guest-agent

- name: Start qemu-guest-agent
  become: true
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
