---

- name: install required packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-docker
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: add docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu noble stable
    state: present

- name: install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true
