---

- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-docker
      - virtualenv
      - python3-setuptools
    state: present
    update_cache: true

- name: Add docker GPG apt key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu noble stable
    state: present

- name: Install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: true
