---

- name: Create admin groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - "{{ users_admin_groups }}"
    - "{{ users_admin_users }}"

- name: Add admin users
  ansible.builtin.user:
    name: "{{ item }}"
    group: "{{ item }}"
    groups: "{{ users_admin_groups | join(',') }}"
    password: '*'
    comment: "ansible-{{ item }}"
    shell: /bin/bash
    append: false
  become: true
  with_items: "{{ users_admin_users }}"

- name: Create ansible tmp directory
  ansible.builtin.file:
    path: /home/{{ item }}/.ansible/tmp
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0700'
  become: true
  become_user: "{{ item }}"
  with_items: "{{ users_admin_users }}"

- name: Create sudoers directory if it does not exist
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    owner: root
    group: root
    mode: '0440'
  become: true

- name: Allow users in admin group to run sudo
  ansible.builtin.template:
    src: 00-admin
    dest: /etc/sudoers.d/{{ item }}
    owner: root
    group: root
    mode: "0440"
  become: true
  with_items: "{{ users_admin_users }}"

- name: Set ssh keys for admin users
  ansible.posix.authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key | join('\n') }}"
    state: present
    exclusive: true
  become: true
  become_user: "{{ item.user }}"
  with_items: "{{ users_users }}"
  when: item.key is defined and item.user in users_admin_users

- name: Configure sshd_config
  ansible.builtin.lineinfile:
    state: present
    path: '/etc/ssh/sshd_config'
    regex: '^(#)?{{ item.key }}'
    line: '{{ item.key }} {{ item.value }}'
  loop:
    - { key: 'StrictModes', value: 'yes' }
    - { key: 'PermitRootLogin', value: 'no' }
    - { key: 'PasswordAuthentication', value: 'no' }
    - { key: 'PermitEmptyPasswords', value: 'no' }
    - { key: 'ChallengeResponseAuthentication', value: 'no' }
    - { key: 'UsePAM', value: 'no' }
    - { key: 'HostbasedAuthentication', value: 'no' }
    - { key: 'AllowGroups', value: 'sshusers sftpusers' }
  become: true
  notify:
    - Restart_sshd
