---

- name: Install dependent packages
  become: true
  ansible.builtin.apt:
    name:
      - software-properties-common
      - git
      - python3-pip
      - virtualenv

# - name: Set Git configs
#   become: true
#   become_user: CI
#   ansible.builtin.command:
#     argv:
#       - git config --global user.name "Mitch"
#       - git config --global user.email "mitch83083@gmail.com"
#   changed_when: true

# # - name: Add ansible repository
# #   become: true
# #   ansible.builtin.apt_repository:
# #     repo: ppa:ansible/ansible
# #     state: present

- name: Install ansible and dependencies
  become: true
  become_user: CI
  ansible.builtin.pip:
    name:
      - ansible
      - ansible-dev-tools
    state: present

- name: Generate locale
  become: true
  ansible.builtin.command: locale-gen en_US.UTF-8
  changed_when: false

# install ansible-dev-tools with pip3 use sudo, or perhaps change to ansible user to install both ansible and ansible-dev-tools
# should I install ansible via pip3 as well?
# also need to figure out locale problem.  possibly sudo locale-gen en_US.UTF-8
# also look at install Semaphore
