---

- name: Install dependent packages
  ansible.builtin.apt:
    name:
      - software-properties-common
      - git
      - python3-pip

- name: Add ansible repository
  ansible.builtin.apt_repository:
    repo: ppa:ansible/ansible
    state: present

- name: Install ansible and dependencies
  ansible.builtin.apt:
    name:
      - ansible
      - ansible-dev-tools
    state: present

# install ansible-dev-tools with pip3 use sudo, or perhaps change to ansible user to install both ansible and ansible-dev-tools
# should I install ansible via pip3 as well?
# also need to figure out locale problem.  possibly sudo locale-gen en_US.UTF-8
# also look at install Semaphore
