- hosts: network
  become: true
  become_method: sudo
  gather_facts: true
  roles:
    - ../roles/apt_upgrade
    # - ../roles/admin_users_groups
    # - ../roles/app_users_groups
    # - ../roles/docker_install
    - ../roles/docker_adguard_home
  vars:
    users_app_users: adguard
    users_app_groups: docker
  vars_files:
    - ../group_vars/admin_users.yml