---

- name: Install adguard home
  hosts: adguard
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: true
  roles:
    - apt_upgrade
    - admin_users_groups
    - app_users_groups
    - docker_install
    - docker_adguard_home
  vars:
    users_app_users: adguard
    users_app_groups: docker
  vars_files:
    - ../group_vars/admin_users.yml
