---

- name: Install traefik
  hosts: traefik
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: true
  roles:
    - apt_upgrade
    - admin_users_groups
    - app_users_groups
    - docker_install
    - docker_compose_setup
    - docker_traefik
  vars:
    users_app_users: docker
    users_app_groups:
      - docker
      - traefik
    app_name: traefik
