---

- name: Set up new users and groups
  hosts: all
  gather_facts: true
  roles:
    - apt_upgrade
    - admin_users_groups
    - app_users_groups
  vars:
    users_app_users: adguard
    users_app_groups: docker
  vars_files:
    - ../group_vars/admin_users.yml
