---

- name: Install whoami
  hosts: test
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: true
  roles:
    - apt_upgrade
    - admin_users_groups
    - app_users_groups
    - docker_install
    - docker_compose_setup
    - docker_traefik_kop
    - whoami
  vars:
    users_app_users: docker
    users_app_groups:
      - docker
    app_name:
      - traefik_kop
      - whoami
