---

name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ballistax/ansible-vault-action@master
        with:
            vault_key: ${{ secrets.VAULT_PASS }}
            args: encrypt /home/CI/ansible/group_vars/vault.yml
