---

- name: Create proxy network
  community.docker.docker_network:
    name: proxy

- name: Copy acme.json
  ansible.builtin.template:
    src: acme.json.j2
    dest: /home/docker/traefik/acme.json
    owner: docker
    group: docker
    mode: '0600'
    force: false

- name: Copy config.yml
  ansible.builtin.template:
    src: config.yml.j2
    dest: /home/docker/traefik/config.yml
    owner: docker
    group: docker
    mode: '0644'
  changed_when: true
  notify: Restart traefik

- name: Copy traefik.yml
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: /home/docker/traefik/traefik.yml
    owner: docker
    group: docker
    mode: '0644'

- name: Deploy traefik with docker compose
  ansible.builtin.template:
    src: docker_compose.yml.j2
    dest: /home/docker/traefik/docker-compose.yml
    mode: "0755"
    owner: docker
    group: docker

- name: Run traefik docker-compose up
  community.docker.docker_compose_v2:
    project_src: /home/docker/traefik
    # recreate: always
    remove_orphans: true
    state: present
